#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_SECI_VERSION=${VERSION_STRING[2]}
ELECTRUM_SECI_VERSION=${ELECTRUM_SECI_VERSION#\'}
ELECTRUM_SECI_VERSION=${ELECTRUM_SECI_VERSION%\'}
export ELECTRUM_SECI_VERSION
