#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_POLIS_VERSION=${VERSION_STRING[2]}
ELECTRUM_POLIS_VERSION=${ELECTRUM_POLIS_VERSION#\'}
ELECTRUM_POLIS_VERSION=${ELECTRUM_POLIS_VERSION%\'}
DOTS=`echo $ELECTRUM_POLIS_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_POLIS_APK_VERSION=$ELECTRUM_POLIS_VERSION.0
else
    ELECTRUM_POLIS_APK_VERSION=$ELECTRUM_POLIS_VERSION
fi
export ELECTRUM_POLIS_VERSION
export ELECTRUM_POLIS_APK_VERSION
