#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_POLIS_VERSION=${VERSION_STRING[2]}
ELECTRUM_POLIS_VERSION=${ELECTRUM_POLIS_VERSION#\'}
ELECTRUM_POLIS_VERSION=${ELECTRUM_POLIS_VERSION%\'}
export ELECTRUM_POLIS_VERSION
